import css from "@eslint/css";
import eslint from "@eslint/js";
import json from "@eslint/json";
import prettierConfig from "eslint-config-prettier/flat";
import importPlugin from "eslint-plugin-import";
import react from "eslint-plugin-react";
import reactHooks from "eslint-plugin-react-hooks";
import globals from "globals";
import tseslint from "typescript-eslint";

const MaxClassesPerFile = 1;
const MaxDepth = 4;
const MaxLines = 10000;
const MaxLinesPerFunction = 1000;
const MaxNestedCallbacks = 3;
const MaxParams = 5;
const IdLength = { min: 1, max: 70 };

export default tseslint.config(
  {
    settings: {
      react: { version: "detect" },
      "import/resolver": {
        typescript: {
          project: "packages/*/{ts,js}config.json",
        },
      },
    },
    // ignores: ["node_modules", "dist"],
    files: ["**/*.{ts,mts,cts,tsx}"],
    extends: [
      eslint.configs.recommended,
      tseslint.configs.strictTypeChecked,
      tseslint.configs.stylisticTypeChecked,
      react.configs.flat.recommended ?? {},
      reactHooks.configs["recommended-latest"],
      importPlugin.flatConfigs.recommended,
    ],
    plugins: { react },
    languageOptions: {
      globals: globals.browser,
      parserOptions: {
        projectService: true,
        tsconfigRootDir: import.meta.url,
        ecmaFeatures: {
          jsx: true,
        },
      },
    },
    rules: {
      "no-constructor-return": "error",
      "no-duplicate-imports": "error",
      "no-inner-declarations": "error",
      "no-promise-executor-return": "error",
      "no-template-curly-in-string": "error",
      "no-unassigned-vars": "warn",
      "no-unmodified-loop-condition": "error",
      "no-unreachable-loop": "error",
      "no-useless-assignment": "error",
      "require-atomic-updates": "error",
      "accessor-pairs": "error",
      camelcase: "error",
      "consistent-return": "error",
      "consistent-this": ["error", "that"],
      curly: ["error", "multi"],
      "default-case": "error",
      "default-case-last": "error",
      eqeqeq: "error",
      "func-name-matching": "error",
      "func-names": ["error", "as-needed"],
      "func-style": ["error", "expression", { allowArrowFunctions: true }],
      "grouped-accessor-pairs": "error",
      "guard-for-in": "off",
      "id-denylist": "error",
      "id-length": ["error", IdLength],
      "id-match": "off",
      "max-classes-per-file": ["error", MaxClassesPerFile],
      "max-depth": ["error", MaxDepth],
      "max-lines": ["error", MaxLines],
      "max-lines-per-function": ["error", MaxLinesPerFunction],
      "max-nested-callbacks": ["error", MaxNestedCallbacks],
      "new-cap": "error",
      "no-alert": "warn",
      "no-bitwise": "error",
      "no-caller": "error",
      "no-case-declarations": "error",
      "no-console": "warn",
      "no-continue": "off",
      "no-delete-var": "error",
      "no-else-return": "error",
      "no-empty": "error",
      "no-empty-static-block": "error",
      "no-eq-null": "error",
      "no-eval": "error",
      "no-extend-native": "off",
      "no-extra-bind": "error",
      "no-extra-boolean-cast": "error",
      "no-global-assign": "error",
      "no-implicit-coercion": "error",
      "no-implicit-globals": "error",
      "no-inline-comments": "off",
      "no-invalid-this": "error",
      "no-labels": "error",
      "no-lone-blocks": "error",
      "no-lonely-if": "error",
      "no-multi-assign": "off",
      "no-multi-str": "off",
      "no-negated-condition": "warn",
      "no-nested-ternary": "error",
      "no-new": "error",
      "no-new-func": "error",
      "no-new-wrappers": "error",
      "no-nonoctal-decimal-escape": "error",
      "no-object-constructor": "error",
      "no-param-reassign": "error",
      "no-plusplus": "off",
      "no-proto": "error",
      "no-restricted-exports": "off",
      "no-restricted-globals": "off",
      "no-restricted-syntax": "off",
      "no-return-assign": "error",
      "no-script-url": "error",
      "no-sequences": "error",
      "no-ternary": "off",
      "no-undef-init": "error",
      "no-undefined": "error",
      "no-underscore-dangle": "off",
      "no-unneeded-ternary": "error",
      "no-useless-call": "error",
      "no-useless-computed-key": "error",
      "no-useless-concat": "error",
      "no-useless-rename": "error",
      "no-useless-return": "error",
      "no-var": "error",
      "no-void": "error",
      "no-warning-comments": ["error", { terms: ["todo"], location: "start" }],
      "object-shorthand": "error",
      "operator-assignment": ["error", "always"],
      "prefer-const": "error",
      "prefer-exponentiation-operator": "error",
      "prefer-numeric-literals": "error",
      "prefer-object-has-own": "error",
      "prefer-object-spread": "error",
      "prefer-regex-literals": "error",
      "prefer-rest-params": "error",
      "prefer-spread": "error",
      "prefer-template": "error",
      radix: ["error", "as-needed"],
      "require-await": "error",
      "sort-imports": "off",
      "sort-keys": "off",
      "sort-vars": "off",
      "symbol-description": "error",
      yoda: "error",
      "no-unused-vars": "off",
      "@typescript-eslint/no-unused-vars": "warn",
      "class-methods-use-this": "off",
      "@typescript-eslint/class-methods-use-this": "error",
      "@typescript-eslint/consistent-type-exports": "error",
      "@typescript-eslint/consistent-type-imports": "error",
      "default-param-last": "off",
      "@typescript-eslint/default-param-last": "error",
      "dot-notation": "off",
      "@typescript-eslint/dot-notation": "error",
      "@typescript-eslint/explicit-function-return-type": "off",
      "@typescript-eslint/explicit-member-accessibility": "error",
      "@typescript-eslint/explicit-module-boundary-types": "off",
      "init-declarations": "off",
      "@typescript-eslint/init-declarations": "off",
      "max-params": "off",
      "@typescript-eslint/max-params": ["error", { max: MaxParams }],
      "@typescript-eslint/member-ordering": "error",
      "@typescript-eslint/method-signature-style": "error",
      "no-array-constructor": "off",
      "@typescript-eslint/no-array-constructor": "error",
      "no-empty-function": "off",
      "@typescript-eslint/no-empty-function": "error",
      "@typescript-eslint/no-explicit-any": "off",
      "no-implied-eval": "off",
      "@typescript-eslint/no-implied-eval": "error",
      "@typescript-eslint/no-import-type-side-effects": "error",
      "no-loop-func": "off",
      "@typescript-eslint/no-loop-func": "error",
      "no-magic-numbers": "off",
      "@typescript-eslint/no-magic-numbers": "error",
      "@typescript-eslint/no-non-null-assertion": "warn",
      "no-shadow": "off",
      "@typescript-eslint/no-shadow": "error",
      "@typescript-eslint/no-unnecessary-qualifier": "error",
      "@typescript-eslint/no-unsafe-type-assertion": "error",
      "no-unused-expressions": "off",
      "@typescript-eslint/no-unused-expressions": "error",
      "@typescript-eslint/no-unnecessary-parameter-property-assignment": "error",
      "no-use-before-define": "off",
      "@typescript-eslint/no-use-before-define": "error",
      "no-useless-constructor": "off",
      "@typescript-eslint/no-useless-constructor": "error",
      "@typescript-eslint/no-useless-empty-export": "warn",
      "no-throw-literal": "off",
      "@typescript-eslint/only-throw-error": "error",
      "@typescript-eslint/parameter-properties": "error",
      "prefer-destructuring": "off",
      "@typescript-eslint/prefer-destructuring": "error",
      "@typescript-eslint/prefer-enum-initializers": "error",
      "prefer-promise-reject-errors": "off",
      "@typescript-eslint/prefer-promise-reject-errors": "error",
      "@typescript-eslint/prefer-readonly": "error",
      "@typescript-eslint/prefer-readonly-parameter-types": "off",
      "@typescript-eslint/promise-function-async": "error",
      "@typescript-eslint/require-array-sort-compare": "error",
      "@typescript-eslint/strict-boolean-expressions": "off",
      "@typescript-eslint/switch-exhaustiveness-check": "error",
      "react/boolean-prop-naming": "off",
      "react/default-props-match-prop-types": "off",
      "react/button-has-type": "error",
      "react/checked-requires-onchange-or-readonly": "error",
      "react/react-in-jsx-scope": "off",
      "react/destructuring-assignment": "error",
      "react/display-name": "error",
      "react/forbid-component-props": "warn",
      "react/forbid-dom-props": "warn",
      "react/forbid-elements": "warn",
      "react/forbid-foreign-prop-types": "off",
      "react/forbid-prop-types": "off",
      "react/forward-ref-uses-ref": "error",
      "react/function-component-definition": "off", //func-style always arrow functions
      "react/hook-use-state": "error",
      "react/iframe-missing-sandbox": "error",
      "react/jsx-boolean-value": "error",
      "react/jsx-fragments": ["error", "syntax"],
      "react/jsx-handler-names": "error",
      "react/jsx-key": "error",
      "react/jsx-max-depth": "off",
      "react/jsx-no-bind": "error",
      "react/jsx-no-comment-textnodes": "error",
      "react/jsx-no-constructed-context-values": "error",
      "react/jsx-no-duplicate-props": "error",
      "react/jsx-no-leaked-render": "error",
      "react/jsx-no-literals": "off",
      "react/jsx-no-script-url": "error",
      "react/jsx-no-target-blank": "error",
      "react/jsx-no-undef": "error",
      "react/jsx-pascal-case": "error",
      "react/jsx-props-no-spread-multi": "error",
      "react/jsx-props-no-spreading": "off",
      "react/jsx-sort-props": "off",
      "react/jsx-uses-react": "off",
      "react/jsx-uses-vars": "error",
      "react/no-access-state-in-setstate": "error",
      "react/no-adjacent-inline-elements": "warn",
      "react/no-array-index-key": "warn",
      "react/no-children-prop": "error",
      "react/no-danger-with-children": "error",
      "react/no-danger": "error",
      "react/no-deprecated": "error",
      "react/no-direct-mutation-state": "error",
      "react/no-find-dom-node": "error",
      "react/no-invalid-html-attribute": "error",
      "react/no-is-mounted": "error",
      "react/no-multi-comp": "error",
      "react/no-namespace": "error",
      "react/no-object-type-as-default-prop": "error",
      "react/no-render-return-value": "error",
      "react/no-set-state": "error",
      "react/no-string-refs": "error",
      "react/no-this-in-sfc": "error",
      "react/no-typos": "error",
      "react/no-unescaped-entities": "error",
      "react/no-unknown-property": "error",
      "react/no-unstable-nested-components": "error",
      "react/no-unused-prop-types": "warn",
      "react/no-unused-state": "warn",
      "react/sort-comp": "error",
      "react/style-prop-object": "error",
      "react/void-dom-elements-no-children": "error",
      "react-hooks/react-compiler": "error",
      "react-hooks/rules-of-hooks": "error",
      "react-hooks/exhaustive-deps": "warn",
      "react/self-closing-comp": "error",
      "import/consistent-type-specifier-style": ["error", "prefer-top-level"],
      "import/default": "error",
      "import/dynamic-import-chunkname": "error",
      "import/enforce-node-protocol-usage": "off",
      "import/export": "error",
      "import/exports-last": "error",
      "import/extensions": "off",
      "import/first": "error",
      "import/group-exports": "error",
      "import/max-dependencies": "error",
      "import/named": "off",
      "import/namespace": "error",
      "import/newline-after-import": "off",
      "import/no-absolute-path": "error",
      "import/no-amd": "off",
      "import/no-anonymous-default-export": "error",
      "import/no-commonjs": "error",
      "import/no-cycle": "off",
      "import/no-default-export": "off",
      "import/no-deprecated": "off",
      "import/no-duplicates": "error",
      "import/no-dynamic-require": "error",
      "import/no-empty-named-blocks": "error",
      "import/no-extraneous-dependencies": "error",
      "import/no-import-module-exports": "error",
      "import/no-internal-modules": "off",
      "import/no-mutable-exports": "error",
      "import/no-named-as-default-member": "error",
      "import/no-named-as-default": "error",
      "import/no-named-default": "error",
      "import/no-named-export": "off",
      "import/no-namespace": "error",
      "import/no-nodejs-modules": "off",
      "import/no-relative-packages": "off",
      "import/no-relative-parent-imports": "off",
      "import/no-restricted-paths": "off",
      "import/no-self-import": "error",
      "import/no-unassigned-import": "error",
      "import/no-unresolved": "error",
      "import/no-unused-modules": "error",
      "import/no-useless-path-segments": "error",
      "import/no-webpack-loader-syntax": "off",
      "import/order": "off",
      "import/prefer-default-export": "off",
      "import/unambiguous": "off",

      //stylistic rule
      "arrow-body-style": "off",
      "prefer-arrow-callback": "off",
      "react/jsx-no-useless-fragment": "error",
      "react/jsx-child-element-spacing": "off",
      "react/jsx-closing-bracket-location": "off",
      "react/jsx-closing-tag-location": "off",
      "react/jsx-curly-brace-presence": "off",
      "react/jsx-curly-newline": "off",
      "react/jsx-curly-spacing": "off",
      "react/jsx-equals-spacing": "off",
      "react/jsx-first-prop-new-line": "off",
      "react/jsx-indent": "off",
      "react/jsx-indent-props": "off",
      "react/jsx-max-props-per-line": "off",
      "react/jsx-newline": "off",
      "react/jsx-one-expression-per-line": "off",
      "react/jsx-props-no-multi-spaces": "off",
      "react/jsx-tag-spacing": "off",
      "react/jsx-wrap-multilines": "off",
    },
  },
  {
    files: ["**/*.json"],
    ignores: ["**/package-lock.json"],
    language: "json/json",
    plugins: {
      json,
    },
    extends: [json.configs.recommended],
    rules: {
      "json/no-empty-keys": "off",
      "json/sort-keys": "off",
      "json/no-duplicate-keys": "off",
      "json/no-unnormalized-keys": "off",
      "json/no-unsafe-values": "off",
      "json/top-level-interop": "off",
    },
  },
  {
    files: ["**/*.css"],
    language: "css/css",
    plugins: { css },
    extends: [css.configs.recommended],
    rules: {
      "css/no-duplicate-imports": "error",
      "css/no-empty-blocks": "error",
      "css/no-important": "error",
      "css/no-invalid-at-rule-placement": "error",
      "css/no-invalid-at-rules": "error",
      "css/no-invalid-named-grid-areas": "error",
      "css/no-invalid-properties": "error",
      "css/prefer-logical-properties": "error",
      "css/relative-font-units": ["error", { allowUnits: ["rem", "em", "%"] }],
      "css/use-baseline": "error",
      "css/use-layers": "error",
    },
  },
  prettierConfig,
);
